### PR TITLE
Update parser component and study plan features description in DG

### LINKED ISSUE #179: Update parser component and study plan features description in Developer Guide

### PR DESCRIPTION
**Pull request by Zhilin-Huang**

### CODE REVIEW

**Comment by g-lilian** [comment]
Somehow I can't load the diagrams, I think my internet has been wonky recently :\

**Comment by Zhilin-Huang** [comment]
> Somehow I can't load the diagrams, I think my internet has been wonky recently :\

I also find that the diagrams in the Markdown files cannot load when I'm reviewing other teammates' PRs and my own PR. I think it will only show up when it is merged. So I just look at the png diagrams themselves haha

**Comment by g-lilian** [comment]
> > Somehow I can't load the diagrams, I think my internet has been wonky recently :\
> 
> I also find that the diagrams in the Markdown files cannot load when I'm reviewing other teammates' PRs and my own PR. I think it will only show up when it is merged. So I just look at the png diagrams themselves haha

I mean the png diagrams don't load as well! :O Can you send them over telegram?
Edit: I managed to load them by opening in a new tab. The files are very huge (8000x4000 :O), I think it will be good to downscale them to normal monitor resolution (definitely less than 2k width, or even smaller).

**Comment by Zhilin-Huang** [comment]
> > > Somehow I can't load the diagrams, I think my internet has been wonky recently :\
> > 
> > 
> > I also find that the diagrams in the Markdown files cannot load when I'm reviewing other teammates' PRs and my own PR. I think it will only show up when it is merged. So I just look at the png diagrams themselves haha
> 
> I mean the png diagrams don't load as well! :O Can you send them over telegram?
> Edit: I managed to load them by opening in a new tab. The files are very huge (8000x4000 :O), I think it will be good to downscale them to normal monitor resolution (definitely less than 2k width, or even smaller).

Oh sure, I didn't notice the size haha. I'll scale them down and upload again! But do they look okay other than the resolution is too high?

**Comment by g-lilian** [comment]
> Oh sure, I didn't notice the size haha. I'll scale them down and upload again! But do they look okay other than the resolution is too high?

Generally looks good! Do you want to include the actor in ParserAndCommandSequenceDiagram? I think this diagram can also be scaled smaller so that the text doesn't look too big compared to the other wider diagrams.
The study plan related diagrams look good as they are, but I'm not sure if you should include something like "confirmation message" on top of the return arrow to the actor? Linking it back to Ui may seem like too much detail, but an empty return arrow seems odd as well (like the user is not receiving anything in response).

**Comment by Zhilin-Huang** [comment]
> > Oh sure, I didn't notice the size haha. I'll scale them down and upload again! But do they look okay other than the resolution is too high?
> 
> Generally looks good! Do you want to include the actor in ParserAndCommandSequenceDiagram? I think this diagram can also be scaled smaller so that the text doesn't look too big compared to the other wider diagrams.
> The study plan related diagrams look good as they are, but I'm not sure if you should include something like "confirmation message" on top of the return arrow to the actor? Linking it back to Ui may seem like too much detail, but an empty return arrow seems odd as well (like the user is not receiving anything in response).

Thanks for the feedback! I'll scale the ParserAndCommandSequenceDiagram smaller. I'm a bit hesitant about including actor in the diagram though - if I want to include `Actor`, then `Main` and `Ui` will need to be added as well since `Actor` does not directly interact with `Parser`. This might be unnecessary as this section should probably focus on the `Parser` and `Command` components only hmmmm

Adding confirmation message is a good idea! Thanks for pointing out :) I'll update accordingly.

**Comment by g-lilian** [comment]
> Thanks for the feedback! I'll scale the ParserAndCommandSequenceDiagram smaller. I'm a bit hesitant about including actor in the diagram though - if I want to include `Actor`, then `Main` and `Ui` will need to be added as well since `Actor` does not directly interact with `Parser`. This might be unnecessary as this section should probably focus on the `Parser` and `Command` components only hmmmm
> 
> Adding confirmation message is a good idea! Thanks for pointing out :) I'll update accordingly.

I see, that is true... Thanks for making the changes :)

**Review by g-lilian — APPROVED** [review]

**Pull request merged**
