### PR TITLE
Update sequence diagrams for get and update study plan

### LINKED ISSUE #122: Update study plan feature description in Developer Guide

### PR DESCRIPTION
**Pull request by Zhilin-Huang**

### CODE REVIEW

**Review by g-lilian — APPROVED** [review]
lgtm, except in the sequence diagram, I'm not sure if the arrow for the actor is supposed to point to the Ui directly instead of Main. I also pointed it to Main in my sequence diag, but idk if that's correct.

**Review by sliu107 — COMMENTED** [review]
For the sequence diagram, I think the calls for `promptUserForRequiredLocalDate()` and `promptUserForRequiredFiedl()` should use seperate activation bars. And the arrow should point to the head of the bar.
Other parts look good to me.

**Comment by Zhilin-Huang** [comment]
Thanks for the feedback! I'll update accordingly

**Comment by Zhilin-Huang** [comment]
> lgtm, except in the sequence diagram, I'm not sure if the arrow for the actor is supposed to point to the Ui directly instead of Main. I also pointed it to Main in my sequence diag, but idk if that's correct.

@g-lilian I moved the arrow from the actor to point to the Ui in the updated version haha 
I think the user is actually interacting with the Ui directly rather the Main, so it might make more sense hmmm

**Review by sliu107 — APPROVED** [review]

**Pull request merged**
